versions: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/marco2704/klingo
    steps:
      - checkout
      - run: make
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/marco2704/klingo
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
